import time
import uuid
import json
from fastapi import APIRouter, HTTPException, BackgroundTasks
from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional, Union
from sse_starlette.sse import EventSourceResponse
from app.models import model_manager

router = APIRouter()

# --- Pydantic Schemas ---

class ChatMessage(BaseModel):
    role: str = Field(..., description="The role of the message author (system, user, assistant)")
    content: str = Field(..., description="The contents of the message")

class ChatCompletionsRequest(BaseModel):
    model: str = Field(..., description="The ID of the model to use (Hugging Face Repository ID)")
    messages: List[ChatMessage] = Field(..., description="A list of messages comprising the conversation history")
    temperature: Optional[float] = Field(0.7, description="What sampling temperature to use (0 to 2)")
    top_p: Optional[float] = Field(0.9, description="An alternative to sampling with temperature, called nucleus sampling")
    max_tokens: Optional[int] = Field(1024, description="The maximum number of tokens to generate")
    stop: Optional[Union[str, List[str]]] = Field(None, description="Up to 4 sequences where the API will stop generating further tokens")
    stream: Optional[bool] = Field(False, description="If set, partial message deltas will be sent as server-sent events")

class ModelLoadRequest(BaseModel):
    repo_id: str = Field(..., description="The Hugging Face Repository ID of the pre-converted OpenVINO model")
    device: Optional[str] = Field(None, description="Hardware target device (AUTO, CPU, GPU, NPU)")

class ModelDownloadRequest(BaseModel):
    repo_id: str = Field(..., description="The Hugging Face Repository ID of the pre-converted OpenVINO model")


# --- API Routes ---

@router.post("/v1/chat/completions", summary="Create chat completion", description="OpenAI-compatible chat endpoint using OpenVINO GenAI")
async def chat_completions(request: ChatCompletionsRequest):
    # Auto-load the requested model if it is different from the currently active model
    if model_manager.active_model != request.model:
        try:
            print(f"Request model '{request.model}' is not active (active: '{model_manager.active_model}'). Loading...")
            model_manager.load_model(request.model)
        except Exception as e:
            raise HTTPException(
                status_code=400, 
                detail=f"Failed to auto-load model '{request.model}'. Ensure the Hugging Face repo contains valid OpenVINO files. Error: {str(e)}"
            )

    request_id = f"chatcmpl-{uuid.uuid4()}"
    created_time = int(time.time())
    params = {
        "temperature": request.temperature,
        "top_p": request.top_p,
        "max_tokens": request.max_tokens,
        "stop": request.stop
    }

    if request.stream:
        async def event_generator():
            try:
                # 1. Send initial chunk outlining assistant role
                yield {
                    "data": json.dumps({
                        "id": request_id,
                        "object": "chat.completion.chunk",
                        "created": created_time,
                        "model": request.model,
                        "choices": [{
                            "index": 0,
                            "delta": {"role": "assistant", "content": ""},
                            "finish_reason": None
                        }]
                    })
                }

                # 2. Iterate and stream chunks generated by OpenVINO
                for token in model_manager.generate_stream(
                    [msg.model_dump() for msg in request.messages], params
                ):
                    yield {
                        "data": json.dumps({
                            "id": request_id,
                            "object": "chat.completion.chunk",
                            "created": created_time,
                            "model": request.model,
                            "choices": [{
                                "index": 0,
                                "delta": {"content": token},
                                "finish_reason": None
                            }]
                        })
                    }

                # 3. Send final finishing chunk
                yield {
                    "data": json.dumps({
                        "id": request_id,
                        "object": "chat.completion.chunk",
                        "created": created_time,
                        "model": request.model,
                        "choices": [{
                            "index": 0,
                            "delta": {},
                            "finish_reason": "stop"
                        }]
                    })
                }
                yield {"data": "[DONE]"}

            except Exception as e:
                yield {
                    "data": json.dumps({
                        "error": {
                            "message": f"Inference Error: {str(e)}",
                            "type": "api_error",
                            "code": 500
                        }
                    })
                }
                yield {"data": "[DONE]"}

        return EventSourceResponse(event_generator())

    else:
        try:
            content = model_manager.generate(
                [msg.model_dump() for msg in request.messages], params
            )
            return {
                "id": request_id,
                "object": "chat.completion",
                "created": created_time,
                "model": request.model,
                "choices": [{
                    "index": 0,
                    "message": {
                        "role": "assistant",
                        "content": content
                    },
                    "finish_reason": "stop"
                }],
                "usage": {
                    "prompt_tokens": -1,
                    "completion_tokens": -1,
                    "total_tokens": -1
                }
            }
        except Exception as e:
            raise HTTPException(status_code=500, detail=f"Generation failed: {str(e)}")


@router.get("/v1/models", summary="List models", description="Returns a list of downloaded models available to load")
async def list_models():
    local_models = model_manager.list_local_models()
    
    # Ensure current active model is represented in the list
    if model_manager.active_model and model_manager.active_model not in local_models:
        local_models.append(model_manager.active_model)

    data = [
        {
            "id": m,
            "object": "model",
            "created": 1700000000,
            "owned_by": "huggingface"
        }
        for m in local_models
    ]
    return {"object": "list", "data": data}


@router.post("/api/models/load", summary="Load/Switch model", description="Downloads (if needed) and loads a model into active memory")
async def load_model(request: ModelLoadRequest):
    try:
        model_manager.load_model(request.repo_id, request.device)
        return {
            "status": "success", 
            "model": request.repo_id, 
            "device": model_manager.active_device
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to load model: {str(e)}")


@router.post("/api/models/download", summary="Download model in background", description="Downloads a model from Hugging Face Hub in the background")
async def download_model(request: ModelDownloadRequest, background_tasks: BackgroundTasks):
    if model_manager.is_downloaded(request.repo_id):
        return {"status": "already_downloaded", "model": request.repo_id}
        
    def bg_download():
        try:
            model_manager.download_model(request.repo_id)
        except Exception as e:
            print(f"Background download failed for model '{request.repo_id}': {str(e)}")

    background_tasks.add_task(bg_download)
    return {
        "status": "download_started", 
        "model": request.repo_id, 
        "detail": "Model download has been scheduled in the background."
    }


@router.get("/api/models/active", summary="Get active model details", description="Returns details about the currently active model and hardware device")
async def get_active_model():
    return {
        "active_model": model_manager.active_model,
        "active_device": model_manager.active_device,
        "local_models": model_manager.list_local_models()
    }
